DROP DATABASE IF EXISTS bd;

CREATE DATABASE bd; 

USE bd;

CREATE TABLE CATEGORIA(
    ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,

    CONSTRAINT PK_CATEGORIA PRIMARY KEY CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE PRODUTO(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    ESTOQUE INTEGER NOT NULL,
    PRECO DECIMAL(6, 2),
    CONSTRAINT PK_PRODUTO PRIMARY KEY(ID)
	);
    
CREATE TABLE COMPRA(
    ID_COMPRA INT NOT NULL AUTO_INCREMENT,

    CONSTRAINT PK_COMPRA PRIMARY KEY COMPRA (ID_COMPRA)
);

CREATE TABLE COMPRA_PRODUTO(
    ID_PRODUTO INTEGER NOT NULL,
    ID_COMPRAS INTEGER NOT NULL

);

    
CREATE TABLE ESTADO(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SIGLA CHAR(2) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY(ID)
	);
    
CREATE TABLE CIDADE(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    ESTADO_ID INTEGER NOT NULL,
    CONSTRAINT PK_CIDADE PRIMARY KEY(ID),
    CONSTRAINT FK_ESTADO_CIDADE FOREIGN KEY(ESTADO_ID) REFERENCES ESTADO(ID)
	); 
    
CREATE TABLE FUNCIONARIO(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    CPF CHAR(11) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    CIDADE_ID INTEGER NOT NULL,
    CONSTRAINT PK_PESSOA PRIMARY KEY(ID),
    CONSTRAINT FK_FUNCIONARIO_CIDADE FOREIGN KEY(CIDADE_ID) REFERENCES CIDADE(ID)
	);
    
CREATE TABLE CLIENTE(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    CPF CHAR(11) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    CIDADE_ID INTEGER NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID),
    CONSTRAINT FK_CLIENTE_CIDADE FOREIGN KEY(CIDADE_ID) REFERENCES CIDADE(ID)
	);

