DROP DATABASE IF EXISTS bd;

CREATE DATABASE bd; 

USE bd;

CREATE TABLE CATEGORIA(
    ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
	
    CONSTRAINT PK_CATEGORIA PRIMARY KEY CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE PRODUTO(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    ESTOQUE INTEGER NOT NULL,
    PRECO DECIMAL(6, 2),
    
    CATEGORIA_ID INTEGER NOT NULL,
    
    CONSTRAINT PK_PRODUTO PRIMARY KEY(ID),
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIA(ID_CATEGORIA)
	);
    
CREATE TABLE COMPRA(
    ID_COMPRA INT NOT NULL AUTO_INCREMENT,

    CONSTRAINT PK_COMPRA PRIMARY KEY COMPRA (ID_COMPRA)
);

CREATE TABLE COMPRA_PRODUTO(
    ID_PRODUTO INTEGER NOT NULL,
    ID_COMPRAS INTEGER NOT NULL);

CREATE TABLE ESTADO(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SIGLA CHAR(2) NOT NULL,
    
    CONSTRAINT PK_ESTADO PRIMARY KEY(ID)
	);
    
CREATE TABLE CIDADE(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    ESTADO_ID INTEGER NOT NULL,
    CONSTRAINT PK_CIDADE PRIMARY KEY(ID),
    CONSTRAINT FK_ESTADO_CIDADE FOREIGN KEY(ESTADO_ID) REFERENCES ESTADO(ID)
	); 
    
CREATE TABLE FUNCIONARIO(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    CPF CHAR(11) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    CIDADE_ID INTEGER NOT NULL,
    CONSTRAINT PK_PESSOA PRIMARY KEY(ID),
    CONSTRAINT FK_FUNCIONARIO_CIDADE FOREIGN KEY(CIDADE_ID) REFERENCES CIDADE(ID)
	);
    
CREATE TABLE CLIENTE(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    CPF CHAR(11) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    CIDADE_ID INTEGER NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID),
    CONSTRAINT FK_CLIENTE_CIDADE FOREIGN KEY(CIDADE_ID) REFERENCES CIDADE(ID)
	);

CREATE TABLE VENDA(
    ID INT NOT NULL AUTO_INCREMENT,
    FUNCIONARIO_ID INTEGER NOT NULL,
    
    CONSTRAINT PK_VENDA PRIMARY KEY(ID),
    CONSTRAINT FK_VENDA_FUNCIONARIO FOREIGN KEY(FUNCIONARIO_ID) REFERENCES FUNCIONARIO(ID)
    );
    
CREATE TABLE VENDA_PRODUTO(
    VENDA_ID INTEGER NOT NULL,
    PRODUTO_ID INTEGER NOT NULL,
    
    CONSTRAINT FK_VENDA_FUNCIONARIO_PRODUTO FOREIGN KEY(PRODUTO_ID) REFERENCES PRODUTO(ID),
    CONSTRAINT FK_VENDA_FUNCIONARIO_VENDA FOREIGN KEY(VENDA_ID) REFERENCES VENDA(ID)
    );
    
CREATE TABLE FORNECEDOR(
    ID INT NOT NULL AUTO_INCREMENT,
    COMPRA_ID INTEGER NOT NULL,
     
    CONSTRAINT PK_FORNECEDOR PRIMARY KEY(ID),
    CONSTRAINT FK_FORNECEDOR_COMPRAS FOREIGN KEY (COMPRA_ID) REFERENCES COMPRA(ID_COMPRA)
    );
    

INSERT INTO CATEGORIA(NOME, DESCRICAO) VALUES
	('CARRO', 'TEM RODAS'),
	('FOTOS', 'SEXY'),
	('TECIDO', 'VESTIMENTO');
    
INSERT INTO PRODUTO(CATEGORIA_ID, NOME, ESTOQUE, PRECO) VALUES
	(1, 'RelampagoMcQueen', 20, 50.00),
	(2, 'PacksDoKairo', 15, 15.00),
	(3, 'MeiaDoAnrey', 10, 10.00);
    
INSERT INTO PRODUTO(CATEGORIA_ID, NOME, ESTOQUE, PRECO) VALUES
	(1, 'RelampagoMcQueen', 20, 50.00),
	(2, 'PacksDoKairo', 15, 15.00),
	(3, 'MeiaDoAnrey', 10, 10.00);
    
INSERT INTO ESTADO(NOME, SIGLA) VALUES
	('PARANA', 'PR'),
    ('MINAS GERAIS', 'MG'),
    ('ACRE','AC');
    
INSERT INTO CIDADE(ESTADO_ID, NOME) VALUES
	(1,'TAMBOARA'),
    (2,'UBERLANDIA'),
    (3,'PARANAVAI');

INSERT INTO FUNCIONARIO(CIDADE_ID, NOME, ENDERECO, TELEFONE, CPF, EMAIL) VALUES
	(1, 'RAFAEL', 'RUA VALO', 44998156478, 12948569848, 'RAFAEL@HOTMAIL.COM'),
    (2, 'JOAO', 'RUA JOJO', 44998486478, 12948569849, 'JOAO@HOTMAIL.COM'),
    (3, 'KAIRO', 'RUA LUA', 44998566478, 12948569847, 'KAIRO@HOTMAIL.COM');
    
INSERT INTO CLIENTE(CIDADE_ID, NOME, ENDERECO, TELEFONE, CPF, EMAIL) VALUES
	(1, 'ROBERTO', 'RUA VALUAN', 44998256478, 12948569841, 'ROBERTO@HOTMAIL.COM'),
    (2, 'JONAS', 'RUA JOJAN', 44998786478, 12948569842, 'JONAS@HOTMAIL.COM'),
    (3, 'KAIRA', 'RUA LUAN', 44998966478, 12948569843, 'KAIRA@HOTMAIL.COM');


