DROP DATABASE IF EXISTS bd;

CREATE DATABASE bd; 

USE bd;
-- ====================================== --
CREATE TABLE CATEGORIA(
    ID_CATEGORIA INT NOT NULL AUTO_INCREMENT
    ,NOME VARCHAR(100) NOT NULL
    ,DESCRICAO VARCHAR(200) NOT NULL
	,STATUS CHAR(1) NOT NULL DEFAULT 'T'
    ,DT_ATUALIZA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    ,CONSTRAINT PK_CATEGORIA PRIMARY KEY CATEGORIA (ID_CATEGORIA)
);
-- ====================================== --
CREATE TABLE PRODUTO(
    ID_PRODUTO INT NOT NULL AUTO_INCREMENT
    ,NOME VARCHAR(50) NOT NULL
    ,ESTOQUE INTEGER NOT NULL
    ,PRECO DECIMAL(6, 2)
    ,ID_CATEGORIA INTEGER NOT NULL
    ,STATUS CHAR(1) NOT NULL DEFAULT 'T'
    ,DT_ATUALIZA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    ,CONSTRAINT PK_PRODUTO PRIMARY KEY(ID_PRODUTO)
    ,CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
); 
-- ====================================== --
CREATE TABLE ESTADO(
    ID_ESTADO INT NOT NULL AUTO_INCREMENT
    ,NOME VARCHAR(50) NOT NULL
    ,SIGLA CHAR(2) NOT NULL
    
    ,CONSTRAINT PK_ESTADO PRIMARY KEY(ID_ESTADO)
);
-- ====================================== --    
CREATE TABLE CIDADE(
    ID_CIDADE INT NOT NULL AUTO_INCREMENT
    ,NOME VARCHAR(50) NOT NULL
    ,ID_ESTADO INTEGER NOT NULL
    
    ,CONSTRAINT PK_CIDADE PRIMARY KEY(ID_CIDADE)
    ,CONSTRAINT FK_ESTADO_CIDADE FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
); 
-- ====================================== --
CREATE TABLE FORNECEDOR(
    ID_FORNECEDOR INT NOT NULL AUTO_INCREMENT
    ,ID_CIDADE INT NOT NULL
    ,NOME VARCHAR(50) NOT NULL
    ,TELEFONE VARCHAR(20) NOT NULL
    ,DOCUMENTO CHAR(18) NOT NULL
    ,STATUS CHAR(1) NOT NULL DEFAULT 'T'
    ,DT_ATUALIZA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
     
    ,CONSTRAINT PK_FORNECEDOR PRIMARY KEY(ID_FORNECEDOR)
    ,CONSTRAINT FK_FORNECEDOR_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID_CIDADE)
); 
-- ====================================== --    
CREATE TABLE COMPRA(
    ID_COMPRA INT NOT NULL AUTO_INCREMENT
	,ID_FORNECEDOR INT NOT NULL
    ,DATA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,STATUS CHAR(1) NOT NULL DEFAULT 'T'
    ,DT_ATUALIZA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    ,CONSTRAINT PK_COMPRA PRIMARY KEY COMPRA (ID_COMPRA)
    ,CONSTRAINT FK_COMPRA_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR (ID_FORNECEDOR)
);
-- ====================================== --
CREATE TABLE COMPRA_PRODUTO(
    ID_PRODUTO INTEGER NOT NULL
    ,ID_COMPRA INTEGER NOT NULL
    ,QNTDE INTEGER NOT NULL
    ,PRECO DECIMAL(6,2) NOT NULL
    ,STATUS CHAR(1) NOT NULL DEFAULT 'T'
    ,DT_ATUALIZA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    ,CONSTRAINT PK_COMPRA_PRODUTO PRIMARY KEY (ID_PRODUTO , ID_COMPRA)
    ,CONSTRAINT FK_COMPRA_PRODUTO_COMPRA FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID_COMPRA)
	,CONSTRAINT FK_COMPRA_PRODUTO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);
-- ====================================== --
CREATE TABLE USUARIO (
	ID_USUARIO INT NOT NULL AUTO_INCREMENT
    ,SENHA VARCHAR(20) NOT NULL
    ,LOGIN VARCHAR(20) NOT NULL
    ,STATUS CHAR(1) NOT NULL DEFAULT 'T'
    ,DT_ATUALIZA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    ,CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);
-- ====================================== --     
CREATE TABLE FUNCIONARIO(
    ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT
    ,NOME VARCHAR(50) NOT NULL
    ,ENDERECO VARCHAR(50) NOT NULL
    ,TELEFONE VARCHAR(15) NOT NULL
    ,CPF CHAR(11) NOT NULL
    ,EMAIL VARCHAR(70) NOT NULL
    ,ID_CIDADE INTEGER NOT NULL
    ,ID_USUARIO INT NOT NULL
    ,STATUS CHAR(1) NOT NULL DEFAULT 'T'
    ,DT_ATUALIZA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    ,CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(ID_FUNCIONARIO)
    ,CONSTRAINT FK_FUNCIONARIO_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
	,CONSTRAINT FK_FUNCIONARIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);
-- ====================================== --
CREATE TABLE CLIENTE(
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT
    ,NOME VARCHAR(50) NOT NULL
    ,ENDERECO VARCHAR(50) NOT NULL
    ,TELEFONE VARCHAR(15) NOT NULL
    ,CPF CHAR(11) NOT NULL
    ,EMAIL VARCHAR(40) NOT NULL
    ,ID_CIDADE INTEGER NOT NULL
    ,STATUS CHAR(1) NOT NULL DEFAULT 'T'
    ,DT_ATUALIZA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    ,CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE)
    ,CONSTRAINT FK_CLIENTE_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
);
-- ====================================== --
CREATE TABLE VENDA(
    ID_VENDA INT NOT NULL AUTO_INCREMENT
    ,ID_FUNCIONARIO INTEGER NOT NULL
    ,DATA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,ID_CLIENTE INT NOT NULL
    ,STATUS CHAR(1) NOT NULL DEFAULT 'T'
    ,DT_ATUALIZA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    ,CONSTRAINT PK_VENDA PRIMARY KEY(ID_VENDA)
    ,CONSTRAINT FK_VENDA_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
	,CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);
-- ====================================== --  
CREATE TABLE VENDA_PRODUTO(
    ID_PRODUTO INTEGER NOT NULL
    ,ID_VENDA INTEGER NOT NULL
    ,QNTDE INT NOT NULL
    ,PRECO DECIMAL(6,2) NOT NULL
    ,STATUS CHAR(1) NOT NULL DEFAULT 'T'
    ,DT_ATUALIZA DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    ,CONSTRAINT PK_VENDA_PRODUTO PRIMARY KEY (ID_PRODUTO , ID_VENDA)
    ,CONSTRAINT FK_VENDA_FUNCIONARIO_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
    ,CONSTRAINT FK_VENDA_FUNCIONARIO_VENDA FOREIGN KEY(ID_VENDA) REFERENCES VENDA(ID_VENDA)
);
-- ====================================== --
    

INSERT INTO CATEGORIA(NOME, DESCRICAO) VALUES
	('CARRO', 'TEM RODAS'),
	('FOTOS', 'SEXY'),
	('TECIDO', 'VESTIMENTO');
    
INSERT INTO PRODUTO(CATEGORIA_ID, NOME, ESTOQUE, PRECO) VALUES
	(1, 'RelampagoMcQueen', 20, 50.00),
	(2, 'PacksDoKairo', 15, 15.00),
	(3, 'MeiaDoAnrey', 10, 10.00);
    
INSERT INTO PRODUTO(CATEGORIA_ID, NOME, ESTOQUE, PRECO) VALUES
	(1, 'RelampagoMcQueen', 20, 50.00),
	(2, 'PacksDoKairo', 15, 15.00),
	(3, 'MeiaDoAnrey', 10, 10.00);
    
INSERT INTO ESTADO(NOME, SIGLA) VALUES
	('PARANA', 'PR'),
    ('MINAS GERAIS', 'MG'),
    ('ACRE','AC');
    
INSERT INTO CIDADE(ESTADO_ID, NOME) VALUES
	(1,'TAMBOARA'),
    (2,'UBERLANDIA'),
    (3,'PARANAVAI');

INSERT INTO FUNCIONARIO(CIDADE_ID, NOME, ENDERECO, TELEFONE, CPF, EMAIL) VALUES
	(1, 'RAFAEL', 'RUA VALO', 44998156478, 12948569848, 'RAFAEL@HOTMAIL.COM'),
    (2, 'JOAO', 'RUA JOJO', 44998486478, 12948569849, 'JOAO@HOTMAIL.COM'),
    (3, 'KAIRO', 'RUA LUA', 44998566478, 12948569847, 'KAIRO@HOTMAIL.COM');
    
INSERT INTO CLIENTE(CIDADE_ID, NOME, ENDERECO, TELEFONE, CPF, EMAIL) VALUES
	(1, 'ROBERTO', 'RUA VALUAN', 44998256478, 12948569841, 'ROBERTO@HOTMAIL.COM'),
    (2, 'JONAS', 'RUA JOJAN', 44998786478, 12948569842, 'JONAS@HOTMAIL.COM'),
    (3, 'KAIRA', 'RUA LUAN', 44998966478, 12948569843, 'KAIRA@HOTMAIL.COM');


